'use client';

// components/creative/ScenarioVideoPlayer.tsx
// Plays the 15-second video generated by Scenario (Seedance 2.0 — start +
// end frame interpolation, 720p, no audio). Simple <video> with autoplay +
// controls, since the model produces the full 15s in one render — no
// chaining, no source swap, no preloader needed.

import { Pause, Play, RotateCcw } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';

import { Button } from '@/components/ui/Button';
import { cn } from '@/lib/utils';

export interface ScenarioVideoPlayerProps {
  videoUrl: string;
  /** Optional poster used while the video is loading. */
  posterUrl?: string | undefined;
  className?: string | undefined;
}

export function ScenarioVideoPlayer({
  videoUrl,
  posterUrl,
  className,
}: ScenarioVideoPlayerProps) {
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const [playing, setPlaying] = useState(true);

  function handleRestart() {
    const video = videoRef.current;
    if (!video) return;
    video.currentTime = 0;
    void video.play().catch(() => setPlaying(false));
    setPlaying(true);
  }

  function togglePlayPause() {
    const video = videoRef.current;
    if (!video) return;
    if (video.paused) {
      void video.play().catch(() => undefined);
      setPlaying(true);
    } else {
      video.pause();
      setPlaying(false);
    }
  }

  // Reset autoplay whenever the source URL changes (regen flow).
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    video.currentTime = 0;
    void video.play().catch(() => setPlaying(false));
    setPlaying(true);
  }, [videoUrl]);

  return (
    <div className={cn('flex flex-col gap-3', className)}>
      <div className="relative mx-auto w-full max-w-[360px] overflow-hidden rounded-xl border border-[var(--color-border)] bg-black shadow-md">
        <div className="relative aspect-[9/16]">
          <video
            ref={videoRef}
            src={videoUrl}
            poster={posterUrl}
            playsInline
            autoPlay
            controls={false}
            onPlay={() => setPlaying(true)}
            onPause={() => setPlaying(false)}
            onEnded={() => setPlaying(false)}
            className="absolute inset-0 size-full object-cover"
          />

          {/* Duration + resolution badge */}
          <span className="pointer-events-none absolute left-2 top-2 inline-flex items-center gap-1 rounded-full bg-black/60 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider text-white backdrop-blur-sm">
            <span className="size-1.5 rounded-full bg-[var(--color-accent)]" />
            15s · 720p
          </span>
        </div>
      </div>

      <div className="flex items-center justify-center gap-2">
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={togglePlayPause}
          aria-label={playing ? 'Pause' : 'Play'}
        >
          {playing ? (
            <Pause className="size-3.5" aria-hidden="true" />
          ) : (
            <Play className="size-3.5" aria-hidden="true" />
          )}
          {playing ? 'Pause' : 'Play'}
        </Button>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={handleRestart}
          aria-label="Restart"
        >
          <RotateCcw className="size-3.5" aria-hidden="true" />
          Restart
        </Button>
      </div>

      <p className="text-center text-[11px] text-[var(--color-muted)]">
        15-second render · start → end frame interpolation via Scenario (Seedance 2.0).
      </p>
    </div>
  );
}
